### ISSUE TITLE
Refactore storage chart

### ISSUE THREAD

**Issue by shakir85** [tinycloud-labs/infrastructure#79]
### Issue
The storage chart is primarily intended for static provisioning. Therefore, a 1:1 PV/PVC mapping is better than relying on K8s' dynamic binding (as currently implemented), which could result in an unintended behavior, such as the application’s PVC binding to the wrong PV.

### Suggestion
- Refactor the chart logic to support only static provisioning. storageClassName should be completely disabled.
- Consider renaming the chart to static-storage or static-persistence.
- Use a single values.yaml key to define the entire persistence profile, structured as follows:

`templates/pv.yaml`
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistence.name }}
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "" # completely disable it
  ...
```

`templates/pvc.yaml`
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "chart.fullname" . }}-pvc
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: ""
  volumeName: {{ .Values.persistence.name }} # Reads a unified name from values
```

`values.yaml`
```
# values.yaml
persistence:
  name: my-specific-pv
  size: 10Gi
  accessMode: ReadWriteOnce
  storageClassName: ""
```
